### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ddi-wtag** [tolgaakyuz/terraform-provider-samson#2]
Hey there!

I was just wondering if there were some form of API documentation for that project? To see which resources could be managed by the provider on Samson, ...

Thanks!

**Comment by danihodovic** [comment]
I don't think there is, you'll have to read the rails code yourself. That's what I had to resort to when building an Ansible provider. The good news is that there has been a series of PRs to improve the JSON API this year.

**Comment by grosser** [comment]
can look through app/controllers/* to see what can be managed and plugins/*/app/controllers/**/*
